# Generated by Django 4.2.3 on 2023-07-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='height',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='Quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
